[project]
name = "btd-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.13.0.90",
    "pyautogui>=0.9.54",
]
